package com.example.accessingdatamysql.controller;

import com.example.accessingdatamysql.entity.AppointmentEntity;
import com.example.accessingdatamysql.entity.DoctorInfoEntity;
import com.example.accessingdatamysql.entity.UserEntity;
import com.example.accessingdatamysql.exceptions.DoctorInfoNotFoundException;
import com.example.accessingdatamysql.exceptions.UserNotFoundException;
import com.example.accessingdatamysql.repository.AppointmentRepository;
import com.example.accessingdatamysql.repository.DoctorInfoRepository;
import com.example.accessingdatamysql.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController// This means that this class is a Controller
@Validated
@RequestMapping(path="/nwt") // This means URL's start with /demo (after Application path)
public class AppointmentController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @Autowired
    private DoctorInfoRepository doctorInfoRepository;

    @Autowired
    private AppointmentRepository appointmentRepository;
    @PostMapping(path="/addAppointment")
    public  @ResponseBody String addNewAppointment(@RequestBody AppointmentEntity appointment){
        appointmentRepository.save(appointment);
        return "Saved";
    }
    @GetMapping(path="/allAppointments")
    public @ResponseBody Iterable<AppointmentEntity> getAllAppointments() {
        // This returns a JSON or XML with the users
        return appointmentRepository.findAll();
    }

}
