package com.example.accessingdatamysql;

import com.example.accessingdatamysql.exceptions.DoctorInfoNotFoundException;
import com.example.accessingdatamysql.exceptions.ReservationNotFoundException;
import com.example.accessingdatamysql.exceptions.UserNotFoundException;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@RestController// This means that this class is a Controller
@Validated
@RequestMapping(path="/nwt") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @Autowired
    private DoctorInfoRepository doctorInfoRepository;

    @Autowired
    private AppointmentRepository appointmentRepository;

    @Autowired
    private EventRepository eventRepository;

    @Autowired
    private ReservationRepository reservationRepository;
    @PostMapping(path="/addUser") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String email, @RequestParam String firstName,
                                            @RequestParam String lastName, @RequestParam Integer type,
                                            @RequestParam String passwordHash) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        UserEntity n = new UserEntity();
        n.setEmail(email);
        n.setFirstName(firstName);
        n.setLastName(lastName);
        n.setType(type);
        n.setPasswordHash(passwordHash);
        userRepository.save(n);
        return "Saved";
    }

    @PostMapping(path="/addDoctor") // Map ONLY POST Requests
    public @ResponseBody String addNewDoctor (@RequestBody DoctorInfoEntity doctor) {

        doctorInfoRepository.save(doctor);
        return "Saved";
    }
    @PostMapping(path="/addAppointment")
    public  @ResponseBody String addNewAppointment(  @RequestBody AppointmentEntity appointment){
        appointmentRepository.save(appointment);
        return "Saved";
    }
    @PostMapping(path="/addEvent")
    public  @ResponseBody String addNewEvent( @RequestBody EventEntity event){
        eventRepository.save(event);
        return "Saved";
    }
    @PostMapping(path="/addReservation")
    public  @ResponseBody String addNewReservation(  @Valid @RequestBody ReservationEntity reservation){
        reservationRepository.save(reservation);
        return "Saved";
    }


    @GetMapping(path="/allUsers")
    public @ResponseBody Iterable<UserEntity> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @GetMapping(path="/allDoctors")
    public @ResponseBody Iterable<DoctorInfoEntity> getAllDoctors() {
        // This returns a JSON or XML with the users
        return doctorInfoRepository.findAll();
    }
    @GetMapping(path="/allAppointments")
    public @ResponseBody Iterable<AppointmentEntity> getAllAppointments() {
        // This returns a JSON or XML with the users
        return appointmentRepository.findAll();
    }
    @GetMapping(path = "/appointments-for-user/{userId}")
    public List<AppointmentEntity> getAppointmentsForUser(@PathVariable int userId){
        UserEntity user=userRepository.findById(userId);
        if (user==null) {
            throw new UserNotFoundException(" Not found user by id " + userId);
        }
        return appointmentRepository.findByUser(user);

    }
    @GetMapping(path = "/appointments-for-doctor/{doctorId}")
    public List<AppointmentEntity> getAppointmentsForDoctor(@PathVariable int doctorId){
        DoctorInfoEntity doctor=doctorInfoRepository.findById(doctorId);
        if (doctor==null) {
            throw new DoctorInfoNotFoundException(" Not found doctor by id " + doctorId);
        }
        return appointmentRepository.findByDoctorInfo(doctor);

    }
    @GetMapping(path = "/allEvents")
    public @ResponseBody Iterable<EventEntity> getAllEvents(){
        return eventRepository.findAll();
    }
    @GetMapping("/events/{eventId}")
    public EventEntity getEvent(@PathVariable int eventId) {
        EventEntity event = eventRepository.findById(eventId);


        if (event == null) {
            throw new ReservationNotFoundException(" Not found event by id " + eventId);
        }

        return event;
    }
    @GetMapping(path = "/allReservations")
    public @ResponseBody Iterable<ReservationEntity> getAllReservations(){
        return reservationRepository.findAll();
    }

    @GetMapping("/reservations/{reservationId}")
    public ReservationEntity getReservation(@PathVariable int reservationId) {
        ReservationEntity reservation = reservationRepository.findById(reservationId);


        if (reservation == null) {
            throw new ReservationNotFoundException(" Not found reservation by id: " + reservationId);
        }

        return reservation;
    }

}