//package com.example.accessingdatamysql.controller;
//import com.example.accessingdatamysql.entity.*;
//import com.example.accessingdatamysql.repository.*;
//
//import com.example.accessingdatamysql.exceptions.ArticleNotFoundException;
//import com.example.accessingdatamysql.exceptions.ForumQuestionNotFoundException;
//import jakarta.validation.Valid;
//import org.springframework.beans.factory.annotation.Autowired;
//import org.springframework.http.HttpStatus;
//import org.springframework.http.ResponseEntity;
//import org.springframework.stereotype.Controller;
//import org.springframework.validation.annotation.Validated;
//import org.springframework.web.bind.annotation.*;
//
//@Controller
//@Validated
//@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
//public class MainController {
//    // This means to get the bean called userRepository
//    // Which is auto-generated by Spring, we will use it to handle the data
//    @Autowired
//    private UserRepository userRepository;
//    @Autowired
//    private DoctorInfoRepository doctorInfoRepository;
//
//    @Autowired
//    private CategoryRepository categoryRepository;
//
//    @Autowired
//    private ArticleRepository articleRepository;
//
//    @Autowired
//    private ForumQuestionRepository forumQuestionRepository;
//
//    @Autowired
//    private ForumAnswerRepository forumAnswerRepository;
//
//    @PostMapping(path="/addUser")
//    public @ResponseBody String addNewUser (@RequestBody UserEntity user) {
//        userRepository.save(user);
//        return "UserEntity Saved";
//    }
//
//    @PostMapping(path="/addDoctor")
//    public @ResponseBody String addNewDoctor (@RequestBody DoctorInfoEntity doctor) {
//
//        doctorInfoRepository.save(doctor);
//        return "Doctor Saved";
//    }
//
//    @PostMapping(path="/addCategory")
//    public @ResponseBody String addNewCategory (@RequestBody CategoryEntity category) {
//        categoryRepository.save(category);
//        return "CategoryEntity Saved";
//    }
//
//    @PostMapping(path="/addArticle")
//    public @ResponseBody String addNewArticle (@Valid @RequestBody ArticleEntity article) {
//        articleRepository.save(article);
//        return "ArticleEntity Saved";
//    }
//
//    @PostMapping(path="/addForumQuestion")
//    public @ResponseBody ResponseEntity<String> addNewForumQuestion (@RequestBody ForumQuestionEntity forumQuestion) {
//        forumQuestionRepository.save(forumQuestion);
//        String message = "{\"message\": \"Forum question saved\"}";
//        // Vrati se JSON objekat pa kasnije kad nam bude trebao odgovor da se parsira
//        return ResponseEntity.status(HttpStatus.CREATED).body(message);
//    }
//
//    @PostMapping(path="/addForumAnswer")
//    public @ResponseBody String addNewForumAnswer (@RequestBody ForumAnswerEntity forumAnswer) {
//        forumAnswerRepository.save(forumAnswer);
//        return "Forum Answer Saved";
//    }
//
//    @GetMapping(path="/allUsers")
//    public @ResponseBody Iterable<UserEntity> getAllUsers() {
//        return userRepository.findAll();
//    }
//
//    @GetMapping(path="/allArticles")
//    public @ResponseBody Iterable<ArticleEntity> getAllArticles() {
//        return articleRepository.findAll();
//    }
//
//    @GetMapping(path="/articles/{articleId}")
//    public @ResponseBody ArticleEntity getArticle(@PathVariable long articleId) {
//        ArticleEntity article = articleRepository.findById(articleId);
//
//        if (article == null) {
//            // Da se vrati u JSON formatu objekat
//            throw new ArticleNotFoundException(" Not found article by id: " + articleId);
//        }
//
//        return article;
//    }
//
//    @GetMapping(path="/allForumQuestions")
//    public @ResponseBody Iterable<ForumQuestionEntity> getAllForumQuestions() {
//        return forumQuestionRepository.findAll();
//    }
//
//    @GetMapping(path="/forumQuestions/{forumQuestionId}")
//    public @ResponseBody ForumQuestionEntity getForumQuestion(@PathVariable long forumQuestionId) {
//        ForumQuestionEntity forumQuestion = forumQuestionRepository.findById(forumQuestionId);
//
//        if (forumQuestion == null) {
//            throw new ForumQuestionNotFoundException(" Not found forum question by id: " + forumQuestionId);
//        }
//
//        return forumQuestion;
//    }
//
//}